In [1]:
import numpy as np

### Creating Arrays

In [53]:
a = np.array((2, 3, 4)) # Or
# a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [54]:
b = np.array([[2.4, 3.4], [4.2, 5.2]], dtype=float)
b

array([[2.4, 3.4],
       [4.2, 5.2]])

In [27]:
c = np.array([[2, 3, 4], [4, 5, 6]], dtype=complex)
c

array([[2.+0.j, 3.+0.j, 4.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

### Get Array Info

In [28]:
# array with element in the range of start=1, stop=15 and reshape with 3 X 5
a = np.arange(1, 16).reshape(3, 5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [29]:
# Get shape of the array.
# For a matrix with n rows and m columns, shape will be (n,m)
a.shape

(3, 5)

In [30]:
# Get the number of axes (dimensions) of the array
a.ndim

2

In [31]:
# Get the type of the elements in the array.
a.dtype.name

'int64'

In [32]:
# Get the size in bytes of each element of the array.
a.itemsize

8

In [7]:
# Get the total number of elements of the array. 
# This is equal to the product of the elements of shape.
a.size


15

In [8]:
# Get the class of the object (array)
type(a)

numpy.ndarray

In [37]:
b = np.array([[6, 7, 8], [8, 9, 0]])
b

array([[6, 7, 8],
       [8, 9, 0]])

In [35]:
type(b)

numpy.ndarray

### Quickly create Numpy arrays

In [34]:
# Create an array of all zeros.
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
# Create an array of all ones.
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [42]:
# Creates an array whose initial content is random and depends on the state of the memory.
np.empty((3, 4))

array([[2.23901381e-316, 0.00000000e+000, 1.03977794e-312,
        9.54898106e-313],
       [1.12465777e-312, 1.03977794e-312, 1.23075756e-312,
        1.03977794e-312],
       [1.12465777e-312, 9.76118064e-313, 1.08221785e-312,
        1.90979621e-312]])

In [43]:
# Create an array of evenly spaced values (start, stop, step)
np.arange(20, 50, 5)

array([20, 25, 30, 35, 40, 45])

In [45]:
# Create evenly spaced samples, calculated over the interval [start, stop].
np.linspace(5, 7)

array([5.        , 5.04081633, 5.08163265, 5.12244898, 5.16326531,
       5.20408163, 5.24489796, 5.28571429, 5.32653061, 5.36734694,
       5.40816327, 5.44897959, 5.48979592, 5.53061224, 5.57142857,
       5.6122449 , 5.65306122, 5.69387755, 5.73469388, 5.7755102 ,
       5.81632653, 5.85714286, 5.89795918, 5.93877551, 5.97959184,
       6.02040816, 6.06122449, 6.10204082, 6.14285714, 6.18367347,
       6.2244898 , 6.26530612, 6.30612245, 6.34693878, 6.3877551 ,
       6.42857143, 6.46938776, 6.51020408, 6.55102041, 6.59183673,
       6.63265306, 6.67346939, 6.71428571, 6.75510204, 6.79591837,
       6.83673469, 6.87755102, 6.91836735, 6.95918367, 7.        ])

In [47]:
# Return a new array of given shape and type, filled with fill_value.
np.full((3, 4), 8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [49]:
# Create a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
# Create a random floats in the half-open interval [0.0, 1.0)
np.random.random((4, 4))

array([[0.2468183 , 0.36701977, 0.93183412, 0.78962524],
       [0.15806474, 0.44566903, 0.92470571, 0.97072685],
       [0.32231927, 0.01580458, 0.29145594, 0.97802657],
       [0.00655899, 0.04669016, 0.8612637 , 0.28326354]])